name: Publish to PyPI

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Extract version from tag
      id: extract_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
    
    - name: Write version to file
      run: echo "${{ steps.extract_version.outputs.VERSION }}" > VERSION
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    
    - name: Build distribution
      run: |
        python setup.py sdist bdist_wheel
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
